const rapl = require('./rapl.js');
rapl.start("1:rapl.js:require");
const os = require("os");
rapl.stop("1:rapl.js:require");
rapl.start("2:rapl.js:require");
const koffi = require('koffi');
rapl.stop("2:rapl.js:require");
rapl.start("4:rapl.js:platform");
const libPath = os.platform() == "win32" ? "rapl_lib.dll" : "./rapl_lib.so";
rapl.stop("4:rapl.js:platform");
rapl.start("6:rapl.js:load");
const lib = koffi.load(libPath);
rapl.stop("6:rapl.js:load");
rapl.start("8:rapl.js:func");
module.exports.start = lib.func('int start_rapl(const char*)');
rapl.stop("8:rapl.js:func");
rapl.start("9:rapl.js:func");
module.exports.stop = lib.func('void stop_rapl(const char*)');
rapl.stop("9:rapl.js:func");
